<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventoryCore\InventoryCore.csproj" />
    <ProjectReference Include="..\InventoryData\InventoryData.csproj" />
    <ProjectReference Include="..\InventoryShared\InventoryShared.csproj" />
  </ItemGroup>

</Project>
